name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Dependencies
      run: |
        sudo apt-get install texlive-latex-base texlive-font-utils texlive-fonts-extra texlive-publishers texlive-science
        
    - name: Generate PDF   
      run: |
        cd thesis
        pdflatex thesis.tex
        bibtex thesis.aux
        pdflatex thesis.tex
        pdflatex thesis.tex
        
    - name: Prepare for deploy
      run: | 
        mkdir deploy
        cp thesis/thesis.pdf deploy/traversaro-phd-thesis.pdf
        
    - name: Deploy
      if: github.event == 'push' && github.ref == 'master'
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy
        
